### ISSUE TITLE
v2.0 - Imports/Exports loader for webpack

### ISSUE THREAD

**Issue by kylemarimon** [vigetlabs/gulp-starter#128]
> Can be used to inject variables into the scope of a module. This is especially useful if third-party modules are relying on global variables like $ or this being the window object.
> _[Webpack imports loader](https://github.com/webpack/imports-loader)_

See [this issue](https://github.com/webpack/imports-loader).

**Comment by DJTB** [comment]
I went about it this way, not sure if it's the same result you're after.
If one file used $, jquery was bundled in that file, if two files used it, jquery was bundled into the shared js.
```js
    // Factor out common dependencies into a shared.js
    webpackConfig.plugins.push(
      new webpack.optimize.CommonsChunkPlugin({
        name: 'shared',
        filename: env === 'production' ? '[name]-[hash].js' : '[name].js',
      }),
      // expose common dependencies from node_modules without needing
      // to use var x = require(dep)
      // they are auto-loaded if the variable below ($, _, Backbone)
      // is used in a file, otherwise never bundled if unreferenced
      new webpack.ProvidePlugin({
        Mn: 'backbone.marionette',
        Backbone: 'backbone',
        $: 'jquery',
        jQuery: 'jquery'
      })
    )
```

**Comment by greypants** [comment]
@DJTB that's pretty cool. When I finally have time to update the README, I'll probably include that bit. Or I guess I could include it in teh webpack config, but just leave it empty or commented out for now. Really useful.

**Comment by stevieg83** [comment]
@DJTB could you share a gist of that in its entirety? I'm struggling with the jQuery dependency stuff

**Comment by DJTB** [comment]
As far as I recall, in the webpack config you can inject modules, such as jQuery, to every loaded module so they're always available. To be honest, these days I always explicitly import dependencies in files - so I wouldn't be using this again.

I don't have any code using this anymore, so no gist to show you. 
https://webpack.github.io/docs/list-of-plugins.html#provideplugin
 
```
new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery: 'jquery'
})
```
This is injecting the jquery module from `/node_modules/` (that you have already `npm install`ed) as `$` and `jQuery` in all your webpack loaded js files so you don't have to individually require it each time.

**Comment by stevieg83** [comment]
@DJTB thanks Duncan. Yeah I tried to import the dependency explicitly as well but always seem to get `$ undefined`

I guess I'll continue to tinker around

**Comment by greypants** [comment]
support for providePlugin is in the `blendid` branch
