### ISSUE TITLE
Support for webpack dev server?

### ISSUE THREAD

**Issue by rstormsf** [vigetlabs/gulp-starter#140]
Suppose we have some API written in node.js(express framework)
How do I add my node.js app,js file to `webpack` task so I can serve some custom `urls` 
P.S.
I use parse.com express framework.

**Comment by rstormsf** [comment]
Or Should I just add 1 more entry point and define new task for web--server?

like this:

```
gulp.task("webpack-dev-server", function(callback) {
  var built = false;
  // modify some webpack config options
  var myConfig = Object.create(config);
  myConfig.devtool = "eval";
  myConfig.debug = true;
  var compiler = webpack(myConfig);
  var server = new WebpackDevServer(compiler, {
    // webpack-dev-server options
    contentBase: "/public",
    // or: contentBase: "http://localhost/",

    hot: true,
    // Enable special support for Hot Module Replacement
    // Page is no longer updated, but a "webpackHotUpdate" message is send to the content
    // Use "webpack/hot/dev-server" as additional module in your entry point
    // Note: this does _not_ add the `HotModuleReplacementPlugin` like the CLI option does. 

    // webpack-dev-middleware options
    quiet: false,
    noInfo: false,
    lazy: true,
    // filename: "hz.js",
    watchDelay: 300,
    publicPath: "/public",
    headers: { "X-Custom-Header": "yes" },
    stats: { colors: true },

    // Set this as true if you want to access dev server from arbitrary url.
    // This is handy if you are using a html5 router.
    historyApiFallback: false,

    // Set this if you want webpack-dev-server to delegate a single path to an arbitrary server.
    // Use "*" to proxy all paths to the specified server.
    // This is useful if you want to get rid of 'http://localhost:8080/' in script[src],
    // and has many other use cases (see https://github.com/webpack/webpack-dev-server/pull/127 ).
    proxy: {
      "*": "http://localhost:9090"
    }
  });
  server.listen(8080, "localhost", function(err) {
    // logger(err, stats)
    browserSync.reload()
    // On the initial compile, let gulp know the task is done
    if(!built) { built = true; callback() }
  });

});
```
in config - added entry - `./cloud/app.js`

still doesn't work for me :-( I'm missing something

**Comment by rstormsf** [comment]
looks like I have to just proxy nodejs server in webpack-dev-server

**Comment by rstormsf** [comment]
hmmm...looks like webpack-dev-server doesn't output files into public/assets/javascripts directory with current config :-(

**Comment by nhunzaker** [comment]
@rstormsf That is the correct path, however! I'm proxying `webpack-dev-server` on most of my projects with [Hapi](http://hapijs.com), the trick is setting up the `publicPath` property and `contentBase` properly

**Comment by nhunzaker** [comment]
It's a bit dated, but on our Capacitor repo we demonstrate this:

Sample config:
https://github.com/vigetlabs/capacitor/blob/master/server/webpack.js#L10

We proxy requests to `/assets` and forward them through to Webpack:

https://github.com/vigetlabs/capacitor/blob/master/server/proxies/assets.js

**Comment by greypants** [comment]
I did this on one of my projects... I'll take a look and see if it makes sense to add here.

**Comment by greypants** [comment]
I just updated this stack to use `webpack-dev-middleware` and  `webpack-hot-middleware` with `BrowserSync`. 

https://github.com/vigetlabs/gulp-starter/pull/257

Not sure if that helps you here, but it might at least give you some clues as to how you could add those middlewares to express instead, combined with BrowserSync's `proxy` option.
