### ISSUE TITLE
Easier importing of css files from node_modules

### ISSUE THREAD

**Issue by MariusRumpf** [vigetlabs/gulp-starter#190]
node-sass / gulp-sass have the ability to provide a custom importer for files. https://github.com/sass/node-sass#importer--v200---experimental
This can come in handy when importing css/sass/scss files from `node_modules`.

There are some modules providing solutions to include enhanced importing with this function.
https://www.npmjs.com/package/node-sass-import-once
https://www.npmjs.com/package/sass-module-importer
https://www.npmjs.com/package/sass-glob-importer

I could get none of them working perfect (since deep custom folder depth), but might be a nice feature as enhancement to import files in sass the short way `@import '~/bootstrap/css/bootstrap.css';`

**Comment by greypants** [comment]
Looks like there's an `includePath` option in `node-sass` that might help us out: https://github.com/vigetlabs/gulp-starter/issues/124#issuecomment-98686011

I never got around to looking into that solution. Give that a shot. Guess it couldn't hurt to have that exposed in the config.

**Comment by renestalder** [comment]
I did it like this in my own Stylus gulp tasks, see the include property, which should be similar to Sass' includePath.

```javascript
  stylus: {
    src: src + "/resources/stylus/**", // files which are watched for changes, but not compiled directly
    main: src + "/resources/stylus/*.{styl, stylus}", // files which are compiled with all their decendants
    dest: dest,
    options: {
      compress: false,
      include: [
        './bower_components/../', // Shortcut references possible everywhere, e.g. @import 'bower_components/bla'
        './node_modules/../'      // Shortcut references possible everywhere, e.g. @import 'node_modules/bla'
      ]
    }
  },
```

With this included, it enables me to reference packages of the node_modules folder or bower folder like this:

```stylus
@import 'node_modules/jeet/stylus/jeet';
```

The thing is to explicit make it a must to reference the node_modules or bower folder. It could be possible that you have same named modules in your own project or different version in bower and node_modules folder. This way also amke the code more readable because it's clear that it imports a node module and not a module from your own project.

**Comment by greypants** [comment]
:+1:

**Comment by splicebison** [comment]
Likewise for SASS:

```
      "sass": {
        "indentedSyntax": true,
        "includePaths": [
          "./node_modules/bourbon/app/assets/stylesheets",
          "./node_modules/bourbon-neat/app/assets/stylesheets"
        ]
      },
```

Then in my base style.scss file I can do:

```
// Vendor
@import "bourbon";
@import "neat";
```

**Comment by nhunzaker** [comment]
:+1: love this. I do it on every project that has NPM packages with stylesheets

**Comment by greypants** [comment]
:clap: does this belong in the README in the sass task section?

**Comment by splicebison** [comment]
@greypants I think that could be good. I scratched my head at first blush until I realized I could add this to the config. It's not obvious when first parsing the files.

**Comment by mathiasvalentin** [comment]
:cake: Perfect! this works for [Susy](http://susy.oddbird.net/) as well.

```
"sass": {
        "indentedSyntax": true,
        "includePaths": [
          "./node_modules/susy/sass"
        ]
      },
´´´

And 

```
@import "susy";
´´´

It would be nice with a comment in README or directly inside the config file.
