### ISSUE TITLE
Use maps for color references

### ISSUE THREAD

**Issue by sjelfull** [vigetlabs/gulp-starter#195]
As we all know, $aLittleTadDarkerBlue is what you usually end up with if we have to use variables for colors.

I really like the [method descibed here](http://erskinedesign.com/blog/friendlier-colour-names-sass-maps/ ) and have been using it successfully for some years now.

```
$_color-base-grey: rgb(229,231,234);

$palettes: (
    purple: (
        base:   rgb(42,40,80),
        light:  rgb(51,46,140),
        dark:   rgb(40,38,65)
    ),
    grey: (
        base:  $_color-base-grey,
        light: lighten($_color-base-grey, 10%),
        dark: darken($_color-base-grey, 10%)
    )
);
````

It might look like this in your stylesheet:
```
a {
    color: palette(purple);
    &:hover {
        color: palette(purple, light);
    }
}
```

**Comment by greypants** [comment]
!()[http://media.giphy.com/media/VLoN2iW8ii3wA/giphy.gif]

**Comment by greypants** [comment]
Closing, as this isn't really an "issue". Feel free to PR though.
