### ISSUE TITLE
Linting gulp-starter

### ISSUE THREAD

**Issue by renestalder** [vigetlabs/gulp-starter#196]
Just a question. Is there any reason why all the .js files of the gulp tasks are missing semicolons at the end of the lines?

**Comment by greypants** [comment]
Personal style preference and slight consolation that I can't write CoffeeScript anymore :) They're not necessary on multi-line code, and actually get added back in during compilation anyway.

The internet has lots of opinions: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=js%20semicolons But in this case, it's really just preference. One less character to type, and one less visual distraction on each line. The final output has them either way.

**Comment by greypants** [comment]
Oh, actually I see you were talking about the gulp files, which just gets run on node. So those aren't complied/processed by anything, they just run. Semi-colons aren't necessary. The actual src/javascripts files are what I was referencing above, where semi-colons get added back in.

**Comment by renestalder** [comment]
Well, I actually only get inspiration for my own gulp tasks here, but sometimes take a whole file from you (with mentioning the origin of course) and noticed that my jslinter/hinter goes crazy. Interesting code style :D.

Thanks for your reply.

**Comment by greypants** [comment]
:+1:
