### ISSUE TITLE
Changes isn't being detected

### ISSUE THREAD

**Issue by sjelfull** [vigetlabs/gulp-starter#197]
I'm on node v0.12.2, and got the latest version of gulp-starter.

I've changed some of the folder names (javascripts -> js), but other than that, the configuration is the same.

When I run `npm run gulp` inside a VM (Homestead + VMWare), the tasks are run just fine. Browersync is telling me that files are being server:
```
[BS] Access URLs:
 ----------------------------------------
       Local: http://localhost:3000
    External: http://192.168.172.130:3000
 ----------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.172.130:3001
 ----------------------------------------
[BS] Serving files from: /home/vagrant/Projects/Project/www/public
```

However, when I change any file, be it a html or scss-file, the changes isn't getting detected.

When googling, I found some issues that might be related:
- https://github.com/floatdrop/gulp-watch/issues/188
- https://github.com/floatdrop/gulp-watch/issues/174

**Comment by sjelfull** [comment]
It does detect changes when editing the files through ssh on the VM. I'm going to test using polling, although that kind of sucks.

**Comment by greypants** [comment]
Hmm... I haven't tried running this inside a VM. Interesting. Let me know what you figure out. I'm not familiar with that setup. @tommymarshall miiiight know. I think he's done Laravel stuff in a VM.

**Comment by sjelfull** [comment]
The files are shared over NFS, and it seems the only sane way to get gulp to detect changes is to enable polling. It slows processing down, though.

After a lot of cursing, I just ended up running it locally, outside of the VM (which caused more cursing).

For anyone that wants to enable polling, you have to add a option into watch.js:
`watch(filePattern, { usePolling: true }, function() { gulp.start(taskName) })`

The options get sent to straight to chokidar. In [the readme](https://github.com/paulmillr/chokidar), it has this to say about usePolling:
> usePolling (default: false). Whether to use fs.watchFile (backed by polling), or fs.watch. If polling leads to high CPU utilization, consider setting this to false. It is typically necessary to set this to true to successfully watch files over a network, and it may be necessary to successfully watch files in other non-standard situations. Setting to true explicitly on OS X overrides the useFsEvents default.`

**Comment by greypants** [comment]
:+1:  Thanks for documenting this. Hope tomorrow is less curse inducing :)

**Comment by greypants** [comment]
@sjelfull Unrelated, but you might be interested in https://github.com/vigetlabs/gulp-starter/issues/203
