### ISSUE TITLE
Use JSON for config for cross language sharing

### ISSUE THREAD

**Issue by greypants** [vigetlabs/gulp-starter#198]
Just ran into this on a Rails project. I wanted to have my Rails asset path helpers read my gulpfile.js/config file, so I converted it to JSON.

**Downside:** It's not JS, so you can't have any logic in the config files (there isn't currently).
**Upside:** Easier cross-language sharing. 

Worth it?

**Comment by tommymarshall** [comment]
Feels fine to me. Makes me wonder what are config files normally saved out as? I feel like yaml is more popular.

**Comment by greypants** [comment]
I went with JSON because you can already `require` it in node. YAML is nice though, and I could use https://github.com/leafty/node-yaml-config

**Comment by tommymarshall** [comment]
Another downside is you can't comment out a task, though you could probably set the value to `false` and then add that check when running defined tasks (ie. if `iconFont` key exists and has a valid input, run the task).
