### ISSUE TITLE
Add Craft asset_path helpers

### ISSUE THREAD

**Issue by greypants** [vigetlabs/gulp-starter#203]
@mzlock or @tommymarshall created these on another project, and they'd be useful to share with the community. One of you want to grab this?

Not sure where these should go... maybe an `extras/craft` folder, with the helper file and a README? I plan on doing the same for Rails.

**Comment by sjelfull** [comment]
Nice, what does it do?

**Comment by greypants** [comment]
Production filenames get hashed: `filename.js` becomes `filename-fdha92379fb2cx84.js`. A `rev-manifest.json` file is generated mapping original filenames to the hashed ones. To reference assets from Twig templates, you need to use a helper to resolve the paths in production.

```twig
<img src="{{'logo.png' | image_path }}">
```

might output something like

```html
<img src="assets/images/logo-ga8203f8vbfa09.png">
```
