### ISSUE TITLE
Handle favicons, and other root level files

### ISSUE THREAD

**Issue by greypants** [vigetlabs/gulp-starter#219]
Favicons and app icons shouldn't get reved, and maybe the whole public folder shouldn't be gitignored? Working on figuring out the best to handle this.

**Comment by mathiasvalentin** [comment]
+1

What about a **root** folder inside the src. The files/folders here gets copied directly into the public folder if anything is newer or missing (gulp-copy)?

We are currently working on a project, where the backend is running asp.net and I't sure would be nice to have files like .config, .cshtml etc. inside the src/public folder (files which isn't being processed by a Gulp task).

**Comment by greypants** [comment]
:+1: I think that's probably the right pattern.

**Comment by mathiasvalentin** [comment]
I'm testing the idea and if it feels like the right solution I'll make a pull request later this week.

**Comment by mathiasvalentin** [comment]
@greypants I managed to implement a simple solution to this issue  https://github.com/vulkanbureau/gulp-starter/commit/94ff45f6b08563b744c6a188b15e4f809216b8da

I basically added an *other* folder inside the *src* folder (name suggestions are very welcome!). This folder is being watched by the added other.js task, which copies files with changes to the public folder - same as the fonts.js task and maybe these tasks could be merged if this seems like the right solution?

**Comment by greypants** [comment]
@mathiasvalentin take a look at #225 

Figured these files shouldn't be reved, so they just get copied over *after* the rev task.

**Comment by mathiasvalentin** [comment]
@greypants Awesome and what simple solution! It works perfectly for me - thanks for making this commit.

**Comment by greypants** [comment]
:+1:
