### ISSUE TITLE
Cannot resolve 'file' or 'directory' in Gulp

### ISSUE THREAD

**Issue by Mannaio** [vigetlabs/gulp-starter#230]
I was wondering why it can not resolve file and directory when i add the js entries in the config.json 

it does not resolve any js file in the js-lib folder

    "js-lib": ["./**/*.js"] or
    "js-lib": ["./js-lib/*.js"]

Se example

"js": {
  "src": "javascripts",
  "dest": "javascripts",
  "extractSharedJs": true,
  "entries": {
    "app": ["./app.js"],
    "page": ["./page.js"],
    "site": ["./site.js"],
    "views": ["./views.js"],
    "js-lib": ["./**/*.js"]
  },
  "extensions": ["js"]
},

It is probably more a question than an issue

I have noticed that there is not a gulp build js in the gulp starter, but we have the css though.

Thanks for the massive work

**Comment by greypants** [comment]
I don't think you can use glob patterns there... they have to be explicit paths. http://webpack.github.io/docs/configuration.html#entry

the `webpackWatch` and `webpackProduction` tasks are what get used for building JS.
