### ISSUE TITLE
how to fixed the node-sass module error?

### ISSUE THREAD

**Issue by was263** [vigetlabs/gulp-starter#237]
5135 error node v5.4.1
5136 error npm  v3.3.12
5137 error code ELIFECYCLE
5138 error node-sass@3.4.2 postinstall: `node scripts/build.js`
5138 error Exit status 1
5139 error Failed at the node-sass@3.4.2 postinstall script 'node scripts/build.js'.
5139 error Make sure you have the latest version of node.js and npm installed.
5139 error If you do, this is most likely a problem with the node-sass package,
5139 error not with npm itself.
5139 error Tell the author that this fails on your system:
5139 error     node scripts/build.js
5139 error You can get their info via:
5139 error     npm owner ls node-sass
5139 error There is likely additional logging output above.
5140 verbose exit [ 1, true ]

**Comment by wridgers** [comment]
You're using Node v5.4.1. This project requires Node v0.12.x.

**Comment by was263** [comment]
OMG....  Tks...

**Comment by greypants** [comment]
That error shows up sometimes when you're switching node versions. You have to `npm rebuild node-sass`. Or `rm -rf node_modules/gulp-sass` then `npm install` again. 

That said, I haven't tested on Node 5.x It does work on Node 4.x though.

**Comment by was263** [comment]
Thanks for greypants..  used rm cmd to finish install...
but now it is new question:(-_-!!!)
> gulp-starter@2.2.0 gulp E:\git\gulpstater
> gulp
module.js:422
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
\\?\E:\git\gulpstater\node_modules\node-sass\vendor\win32-ia32-47\binding.node
    at Error (native)
    at Object.Module._extensions..node (module.js:422:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\git\gulpstater\node_modules\node-sass\lib\index.js
:16:15)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "gulp"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! gulp-starter@2.2.0 gulp: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gulp-starter@2.2.0 gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gulp-starter package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls gulp-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\git\gulpstater\npm-debug.log

**Comment by greypants** [comment]
```
npm ERR! node v5.4.1
npm ERR! npm v3.3.12
```

I haven't tested this with node 5 and npm 3 - that's probably your issue. The package.json specifies Node 0.12.7, but it should work up to Node 4.x.
