### ISSUE TITLE
.scss dont work

### ISSUE THREAD

**Issue by nachoumaran** [vigetlabs/gulp-starter#238]

**Comment by nachoumaran** [comment]
Cannot GET /css/global.css

**Comment by mathiasvalentin** [comment]
any error messages in terminal?

**Comment by nachoumaran** [comment]
the problem is that reads .sass and not .scss

This is the terminal error: 

[11:40:28] gulp-notify: [Error running Gulp] Error in plugin 'gulp-sass'
Message:
    src/css/global.css.scss
Error:
Invalid CSS after ".navbar-default {":
expected "}", was "{"
        on line 3 of stdin
>> .navbar-default { {
   -----------------^

**Comment by mathiasvalentin** [comment]
Oh yes! I have been experiencing this problem as well. The global.scss is being interpreted as a sass file - which throws that error. 
A quick solution is to change the global file back to .sass format and then import scss files into it. This will work, until we find a solution.

**Comment by nachoumaran** [comment]
Thanks for the help ;)

**Comment by greypants** [comment]
If you're not using sass at all, you can remove this option: https://github.com/vigetlabs/gulp-starter/blob/master/gulpfile.js/config.json#L37

(or set it to false)

That should fix it.

**Comment by mathiasvalentin** [comment]
Perfect! That fixed it :+1: 
```
"indentedSyntax": false;
```

**Comment by greypants** [comment]
:+1:
