### ISSUE TITLE
iconFont  not work on windows platform.

### ISSUE THREAD

**Issue by wrongch** [vigetlabs/gulp-starter#242]
On my windows 10, 
    `gulp`
can run successfully.

but look into the  generated `_icons.sass`, I found the fontpath is not correct, 

`  
src: url("..\fonts/icons.eot")
`
the `f` of the `fonts`, is escaped by the `\`.

**Comment by MariusRumpf** [comment]
Same for mac os since I did a `npm update`.

**Comment by wrongch** [comment]
closed #243
