### ISSUE TITLE
reloading json data

### ISSUE THREAD

**Issue by builtbylane** [vigetlabs/gulp-starter#246]
any ideas on a way of updating JSON data in the html task without having to restart gulp?

**Comment by greypants** [comment]
I'd have to look... but off the top of my head, I know that if you are doing `require('./foo.json')`, the result gets cached. If you want to read it fresh every time, you need to use `fs.readFileSync`

```
var fs = require('fs');
var obj = JSON.parse(fs.readFileSync('file', 'utf8'));
```

Ran into this once on another project. StackOverflow for the win: http://stackoverflow.com/questions/10011011/using-node-js-how-do-i-read-a-json-object-into-server-memory

**Comment by greypants** [comment]
Hmm... looks like I'm already doing that.

https://github.com/vigetlabs/gulp-starter/blob/master/gulpfile.js/tasks/html.js#L23

Maybe it's a watcher issue? Kinda confusing, but make sure you have `json` listed here: https://github.com/vigetlabs/gulp-starter/blob/master/gulpfile.js/config.json#L49

That config bit's not clear... but the watcher uses the file extensions listed in each tasks config object.

**Comment by builtbylane** [comment]
OKay thanks. I'll let you know what I find

**Comment by greypants** [comment]
Changes to `src/html/data/global.json` are working for me in my example code. Was the example broken, or your specific implementation? Closing, but re-open if this is still an issue for you with the latest from `master`, and let me know what system (windows, ubuntu, osx, etc...) and version of node your'e on.
