### ISSUE TITLE
deprecated WARNs

### ISSUE THREAD

**Issue by avdeev** [vigetlabs/gulp-starter#247]
`npm WARN  deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

`npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade                                                                              to lodash@^4.0.0.`

**Comment by avdeev** [comment]
`npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm`

**Comment by avdeev** [comment]
And more warnings...

**Comment by greypants** [comment]
Yeah, those are annoying. Will addres.

**Comment by greypants** [comment]
Updated every dependency to the latest. Any remaining warnings are from package dependencies.
