### ISSUE TITLE
Html not updating when there are too many pages

### ISSUE THREAD

**Issue by chaelli** [vigetlabs/gulp-starter#251]
Hi

We have lots of pages and we noticed that the last ones (probably in alphabetical sorting) are not updated if the html should change (update in json or html).
To reproduce the issue you can use a clean clone and just copy the page.html file 100 times. Then you create a zpage.html and load this page in the browser. Then you open the zpage.html in an editor and change something... the page will not be updated in the browser and reloading does not help either.

I tested this on Windows 10 - a friend of mine is testing it on his mac now as well. Will update the ticket with the information soon.

**Comment by ndyne** [comment]
Hello
Just ran it on my OSX 10.11. Same issue here. :(

**Comment by greypants** [comment]
weeeeeird. Try updating `gulp-nunjucks-render` and `gulp-watch` to the latest versions and let me know what happens. I haven't upgraded dependencies in a while.

**Comment by chaelli** [comment]
Hi @greypants 

I tested it - same issue (I had to move the layout for it to work.. but then again.. it didn't update :(

**Comment by greypants** [comment]
@chaelli can you let me know if this was resolved by #256 ?

**Comment by chaelli** [comment]
@greypants sadly not :(

**Comment by greypants** [comment]
:crying_cat_face:

**Comment by JerroldLee** [comment]
Having the same problem

**Comment by JerroldLee** [comment]
Is the problem resolved? @chaelli

**Comment by chaelli** [comment]
Sadly not. But I also haven't really found time to search for the root cause.

**Comment by JerroldLee** [comment]
I have solved the problem，you should edit the "html" task (https://github.com/vigetlabs/gulp-starter/blob/master/gulpfile.js/tasks/html.js)，change the position of "pipe(gulp.dest(paths.dest))" and ".pipe(browserSync.stream())"(line 39 and 40)，restart your server and it will works well.

**Comment by JerroldLee** [comment]
@chaelli

**Comment by greypants** [comment]
Nice! @JerroldLee by "change the position" do you mean switch their order so `browserSync.stream()` is first?:

```js
    .pipe(browserSync.stream())
    .pipe(gulp.dest(paths.dest))
```

**Comment by ndyne** [comment]
@JerroldLee do you mean switch the position of lines 39 and 40 as stated by @greypants? I tried this in our test case and it doesn't seem to help :( 

File 53 (55 if you count the layouts and macros folders) and onward isn't updating until you stop and run develop or production...

**Comment by JerroldLee** [comment]
Yes, restart your server after the adjustment. @greypants @ndyne

**Comment by ndyne** [comment]
Hi @JerroldLee 
I did restart but it didn't help ;( Node 5.10.1 on OSX 10.11.4. Haven't yet tested Node 6.*

**Comment by mdmoreau** [comment]
Try using ```.on('end', browserSync.reload);``` instead of the stream.  I was having the same issue in a workflow I use, and this seemed to fix the issue.

Nunjucks task: https://github.com/mdmoreau/static/blob/master/gulpfile.js/tasks/nunjucks.js

**Comment by ndyne** [comment]
No luck. I tried both @mdmoreau 's and @JerroldLee 's tipps, updated to node 6.* ran npm install and retarted the servers but the issues remain. There's a good chance I'm doing something wrong so I'm handing this over to whomever has time to make a few tests on their own... @greypants or @chaelli ?

**Comment by mdmoreau** [comment]
I think my problem may have been slightly different actually.  For me Browser Sync would reload too early, but doing a manual refresh in the browser would show the updated page.  I also had issues with Chrome using cached pages after refresh, but was able to fix that by keeping dev tools open and disabling cache in the network tab.

You might want to try using ```.pipe(browserSync.stream({once: true}))``` to keep reloading to once per stream (see https://browsersync.io/docs/api/#api-stream).  If the files themselves aren't being updated though the problem might be totally unrelated.  Could be an issue with gulp-nunjucks-render - maybe try swapping out with https://www.npmjs.com/package/gulp-nunjucks-html which is what I've been using.

**Comment by AminulBD** [comment]
When you reload again the page, Then, Update will effect on the page. But, you can add the gulp-wait package if you need to set time,

**Comment by mdmoreau** [comment]
@AminulBD that's the issue I was having that ```.on('end', browserSync.reload);``` solved.  It looked like Browser Sync was starting the reload after only the first page had been updated.  This can be a problem if you have a bunch of pages and the reload fires before they one you're working on has been changed, requiring you to manually refresh.  Using the above method of reloading should wait until all of the pages have been processed before firing the reload.

**Comment by AminulBD** [comment]
@mdmoreau hmm, That's the great solution :+1:

**Comment by tampham47** [comment]
@mdmoreau your solution works well, thanks. Anyway, I think we can make a better solution for the large bunch of pages, that dont need to reload. 😸

**Comment by greypants** [comment]
If you guys can confirm this solves the issue, feel free to open a Pull Request. I'm pretty busy and might not get to it right away. Thanks for looking into this!

**Comment by tampham47** [comment]
It just a hot fix at the large bunch of pages. Incase amount of pages less than 50, the current works better.

**Comment by mdmoreau** [comment]
I've had the problem pop up while there were only 3 or 4 pages, so my guess is it depends on the project/machine.

Ideally you could use gulp-changed to only update some files, but extending, including, etc makes that not really work, as only updating an include file wouldn't update the page it's included on.  It looks like jade has a plugin to handle that situation with https://github.com/juanfran/gulp-jade-inheritance, but I haven't been able to find anything for Nunjucks.
