### ISSUE TITLE
How add bootstrap and other library dependency in jquery

### ISSUE THREAD

**Issue by Killerblade** [vigetlabs/gulp-starter#252]
Please really need your help .
app.js
`
import './asyncModules'
import exclaimify from './exclaimify'
import $ from 'jquery';
import bootstrap from 'bootstrap'
`
When you start 

> ReferenceError: jQuery is not defined

Show an example of how to please add external library dependencies. I would be very grateful for the help

**Comment by greypants** [comment]
You need to install them and save them to your `package.json`.

```
npm install jquery --save
npm install bootstrap --save`
```

**Comment by Killerblade** [comment]
Yes, they are set in this manner

**Comment by Killerblade** [comment]
@greypants
How can it be if they are installed and stored in package.json and connected in app.js and still get the error ReferenceError: jQuery is not defined

**Comment by greypants** [comment]
Oh - Bootstrap is probably expecting `jQuery` to exist on `window`. There are a couple of ways you can do that. Either through the the webpack config, or more simply can manually do it with `require` 

```js
const jQuery = require('jquery')
global.jQuery = jQuery

const bootstrap = require('bootstrap')
```

You can't use `import` because they all have to appear at the top of the file, so you couldn't set that global before `import`ing bootstrap.

**Comment by Killerblade** [comment]
Thanks. @greypants 
`const jQuery = require('jquery'); 

global.jQuery = jQuery;
global.$ = jQuery;`

Solve my problem

**Comment by greypants** [comment]
:+1:

**Comment by mathiasvalentin** [comment]
I'm using the webpack.ProvidePlugin for this. 
https://webpack.github.io/docs/shimming-modules.html

**Comment by greypants** [comment]
:point_up: That's the Webpack way I was referring to, and really the better way to do it. Thanks @mathiasvalentin!
