### ISSUE TITLE
Added dependancy to css task but it doesn't running during watch

### ISSUE THREAD

**Issue by dan-gamble** [vigetlabs/gulp-starter#253]
I've changed my `css.js` to: `gulp.task('css', ['stylelint'], cssTask)`

*stylelint.js*
```js
var config = require('../config')
if (!config.tasks.css) return

var gulp = require('gulp')
var postcss = require('gulp-postcss')
var path = require('path')
var reporter = require('postcss-reporter')

var paths = {
  src: path.join(config.root.src, config.tasks.css.src, '/**/*.' + config.tasks.css.extensions),
  dest: path.join(config.root.dest, config.tasks.css.dest)
}

var styleLintTask = function () {
  var processors = [
    require('stylelint'),
    reporter({clearMessages: true})
  ]

  return gulp.src(paths.src)
    .pipe(postcss(processors))
}

gulp.task('stylelint', styleLintTask)
module.exports = styleLintTask
```

When i run the `default` task the `stylelint` task gets run but when it comes to watching and i make an edit to the CSS all i get is: `[BS] 2 files changed (app.css)` and occasionaly i get the `stylelint` task running too but more than often it doesn't run.

Any ideas on why it only runs sporadically?

**Comment by greypants** [comment]
Hmm... sounds like the `cssTask` isn't waiting for `stylelint` to complete before running like it should. Nothing is jumping out at me as being clearly wrong. Usually it's forgetting to return a stream, but you're doing that. OH. I bet I know: you need to add `styleLint` as a dependency of cssTask.

```js
gulp.task('cssTask', ['stylelint'], function() {
   // css task stuff here... 
})
```

Check out the bottom of this section of the docs: https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support

Hope that's helpul! Closing this since it's not a gulp-starter specific issue. Good luck!

**Comment by dan-gamble** [comment]
Thanks! I currently do have `gulp.task('css', ['stylelint'], cssTask)` as a dependancy but it doesn't run, i'll have a look through the async docs though, thanks :)

**Comment by greypants** [comment]
You could always brute force it with `gulp-sequence`, like I'm doing in the `default` and `production` tasks.   I find that easier to maintain. Thankfully Gulp 4 will work more like that.

**Comment by dan-gamble** [comment]
Tried `gulp-sequence` tried upgrading `gulp-starter` to Gulp 4, tried a lot but can't seem to get it to work at all :D.

The gulp 4 thing did work to be fair, but a few other things broke. But it's my issue, not yours ;)

**Comment by greypants** [comment]
OH - I haven't tried upgrading to gulp 4 yet, so no idea how that'd go. But changing your css task to something like


```js
var gulp            = require('gulp')
var gulpSequence    = require('gulp-sequence')

gulp.task('cssTask', function(cb) {
  gulpSequence('styleLint', 'compileSass',  cb)
})
```
Or something like that should work. Or you can just put everything in one task just add that pipe to the top of the list.


```js

 var processors = [
    require('stylelint'),
    reporter({clearMessages: true})
  ]

var cssTask = function () {
  return gulp.src(paths.src)
    .pipe(postcss(processors))
    .pipe(sourcemaps.init())
    .pipe(sass(config.tasks.css.sass))
    .on('error', handleErrors)
    .pipe(autoprefixer(config.tasks.css.autoprefixer))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(paths.dest))
    .pipe(browserSync.stream())
}
```

Since you're using postcss, you could also add autoprefixer there and remove the gulp plugin version if you wanted.

**Comment by dan-gamble** [comment]
So i tried:

```
gulp.task('cssTask', cssTask)
gulp.task('css', function (cb) {
  console.log(cb)
  gulpSequence('stylelint', 'cssTask', cb)
})
```

The `console.log()` is there to see when it gets called.

The output i get when i run gulp and then change some CSS files:

```
[16:31:59] Using gulpfile ~/Workspace/undo-software/gulpfile.js
[16:31:59] Starting 'default'...
[16:31:59] Starting 'clean'...
[16:31:59] Finished 'clean' after 23 ms
[16:31:59] Starting 'fonts'...
[16:31:59] Starting 'images'...
[16:31:59] Finished 'fonts' after 18 ms
[16:31:59] Finished 'images' after 67 ms
[16:31:59] Starting 'css'...
[Function]
[16:31:59] Starting 'stylelint'...
[16:32:00] Starting 'webpack:watch'...
[16:32:03] Hash: c81b501cc88e343ec72a
Version: webpack 1.12.14
Time: 3410ms
        Asset     Size  Chunks             Chunk Names
       app.js   703 kB    0, 1  [emitted]  app
    shared.js  3.71 kB       1  [emitted]  shared
   app.js.map   855 kB    0, 1  [emitted]  app
shared.js.map  3.75 kB       1  [emitted]  shared
chunk    {0} app.js, app.js.map (app) 678 kB {1} [rendered]
    [0] multi app 28 bytes {0} [built]
    [1] .. shortened because it's way big.
[16:32:03] Compiled with webpack in 3.41 s
[16:32:03] Finished 'webpack:watch' after 3.45 s
[16:32:04] Finished 'stylelint' after 4.35 s
[16:32:04] Starting 'cssTask'...
[16:32:05] Finished 'cssTask' after 669 ms
[16:32:05] Finished 'css' after 5.02 s
[16:32:05] Starting 'browserSync'...
[16:32:05] Finished 'browserSync' after 56 ms
[16:32:05] Starting 'watch'...
[16:32:05] Finished 'watch' after 14 ms
[16:32:05] Finished 'default' after 5.19 s
[BS] Proxying: http://0.0.0.0:8000
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.19:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.19:3001
 -------------------------------------
[BS] 2 files changed (app.css, wysiwyg.css)
[BS] 2 files changed (app.css, wysiwyg.css)
```

I get the console.log on the initial build but once it hits the watch it doesn't seem to go through that task at all. Does the watcher use the export (`var cssTask = function ()  {}`) as opposed to the task name at all?

**Comment by dan-gamble** [comment]
I've worked out it does run on the `module.exports` instead of the actual task.

It's like i kinda want to change:

```
      watch(glob, function() {
       require('./' + taskName)()
      })
```

To run the gulp task instead of require the function it exports

**Comment by greypants** [comment]
Oh yeah, that'd be the issue. There was a reason I did it that way... which I don't recall...

I'd use the gulp-sequence method or move things into one task, and make sure that's the function that gets exported.

**Comment by dan-gamble** [comment]
Haha :D

The gulp-sequence method still doesn't work because it's the function that gets run. I'd need to find a way to get the watch to run the task vs the function or like you say merge into a singular function. Or go the balls to the walls way and upgrade it all to Gulp 4.

Thanks for your help though :)

**Comment by greypants** [comment]
Hm... I might be missing something, but Gulp-sequence should work because would called in the exported function. Your main css function/task would look like this:

```js
var allMyCSStasks = function(cb) {
  gulpSequence('cssLint', 'sassStuff', 'someOtherCSSthing', cb)
}

gulp.task('css', allMyCSStasks)
module.exports = allMyCSStasks
```

Then the watcher would call that `allMyCSSTasks` function, which calls all your sub-tasks in order with `gulpSequence`.

**Comment by dan-gamble** [comment]
Ahh that makes sense, i was doing the gulpSequence on the `gulp.task()`. Not at work now but i'll try that variant instead. That at least makes more sense than what i was doing before :)
