### ISSUE TITLE
gulp hangup if nunjucks has error

### ISSUE THREAD

**Issue by AminulBD** [vigetlabs/gulp-starter#254]
Hello,

If template is missing then, gulp hang-up and displaying this error

![gulp-nunjucks-err](https://cloud.githubusercontent.com/assets/5006546/13867843/3d0e5f20-eced-11e5-827a-19a0cd56f3ff.PNG)

Did you notice this?

**Comment by greypants** [comment]
Hmm... that is annoying. It shouldn't stop the process. I thought I was catching errors here: https://github.com/vigetlabs/gulp-starter/blob/master/gulpfile.js/tasks/html.js#L31-L33

Something to look into.

**Comment by AminulBD** [comment]
Hello,

I was tried many ways, but the "Template render in plugin 'gulp-nunjucks'" coming extra and tried to format the handleErrors. But, Didn't get any good result.

BTW, gulp-nunjucks-html is working fine here without any issue.

**Comment by greypants** [comment]
Fixed in #256
