### ISSUE TITLE
Include config.json dynamicaly

### ISSUE THREAD

**Issue by radiocity** [vigetlabs/gulp-starter#255]
Ehlo. I recommend to include config.json dynamically, because after starting gulp, it includes current config.json and does not respond to any changes in it.

~~Google helps me to translate this issue. Sorry :P~~

**Comment by greypants** [comment]
Interesting thought. Ideally, you'd set up your config.json once and never have to touch it again. Including it dynamically would slow recompiles and add some perhaps unnecessary complexity. Probably not going to do this, but feel free to open a PR if you've done it. I'm open to seeing how it would work.

**Comment by radiocity** [comment]
I dont use webpack for some reasons. Gulp concatinate js into bundles and wrap em into IIFE optionally. So we use config.json to describe this pisa tower...
