### ISSUE TITLE
Wepback Path issue on Windows

### ISSUE THREAD

**Issue by greypants** [vigetlabs/gulp-starter#262]
@chaelli's description copied from https://github.com/vigetlabs/gulp-starter/pull/257#issuecomment-202039278

> since this update I get a 404 on the http://localhost:3000/javascripts/app.js - there's also no "javascripts" folder in the "public" folder. 
Any idea what could be wrong? the paths seem to be correct...
 
**Update:**     
> ouch.. found the issue.. Windows again ;)
just add ".replace(/\/g, '/')" to the following line in webpack-multi-config.js to fix it:
var publicPath = path.join(config.tasks.js.dest, '/')

**Comment by greypants** [comment]
Good ol' Windows paths. I thought `path.join` should normalize that. Does this also work?

```js
var publicPath = path.normalize(config.tasks.js.dest +  '/')
```

I forget why I needed that trailing slash... I'm sure I added it for a reason at some point. But I'll try it again without it.

**Comment by chaelli** [comment]
nope, normalize doesn't work - I guess normalize replaces all / and \ with the appropriate character for the current OS. So for windows it will replace all with \ => but as this "path" is not used as "path" but as "url", it doesn't work.

**Comment by greypants** [comment]
ooooh. Sounds like I need `url.resolve` then: https://nodejs.org/api/url.html#url_url_resolve_from_to

**Comment by greypants** [comment]
Ah. Right, we're converting a windows path to a URL. Your suggestion sounds like it should be good enough. Will add.
