### ISSUE TITLE
Using jQuery

### ISSUE THREAD

**Issue by be-codified** [vigetlabs/gulp-starter#264]
I would like to use jQuery from node_modules. How do I include it in the project?

Thank you for your assistance.

**Comment by greypants** [comment]
If you're using ES6:
```js
import $ from `jquery`
```

or ES5 

```
var $ = require('jquery')
```

If you're wanting to put `$` on window to make it globally accesible, see comments in https://github.com/vigetlabs/gulp-starter/issues/252
