### ISSUE TITLE
Angular Conflicts with Nunjucks

### ISSUE THREAD

**Issue by lloy0076** [vigetlabs/gulp-starter#267]
Firstly, let me just say this is awesome and thank you to the author and other contributors. In my use case, I wanted to see if I could build an AngularJS application.

This mostly worked except what I discovered was that the "html.js" task (in gulpfile.js/tasks/html.js) hard coded the "Nunjucks" render call and there wasn't any easy way to prevent this via configuration [i.e. one couldn't turn it off in config.json].

Unfortunately, this makes Angular's default templating (using {{ and }}) "go away".

What I did to fix this was change "html.js" to (including only lines 10-13):

```
 10 var path         = require('path')
 11 //var render       = require('gulp-nunjucks-render')
 12 var render       = require('gulp-empty') // Don't and make sure this is installed
 13 var fs           = require('fs')
```

A better way would be to add some sort of configuration switch but am wondering if this is worth doing (before I do a pull request, figure out how to test it properly etc etc).

On a side note, it seems that Nunjucks is/may be rendering in the gulpfile.js/iconFont/generateIconSass.js as well (but this doesn't appear to make anything Angular fall over).

I'd make a plunkr to demonstrate this but I think it's a fair diagnosis to say that the Nunjucks vs Angular templates conflicted with each other.

**Comment by greypants** [comment]
Hmm... so nunjucks templating would still be useful if there wasn't a conflict, right? 

I googled Angular Nunjucks and found https://github.com/mozilla/nunjucks/issues/397. Looks like there is a configuration option to change the syntax. https://mozilla.github.io/nunjucks/api.html#customizing-syntax

Seems like we should expose Nunjucks options in the `config.json` file. Would that solve it for you?

**Comment by lloy0076** [comment]
Angular can be reconfigured as well but it would be useful, I should suppose, to be able to configure nunjucks from the config.json as I'm sure there's other configuration variables it has that might be useful to others.
