### ISSUE TITLE
`No implicit conversion of nil into string` when variable passed in to gulp_image_path

### ISSUE THREAD

**Issue by craigmdennis** [vigetlabs/gulp-starter#276]
I'm having issues using the Rails helper when the image path is passed in using a variable. I'm trying to produce a reduced test case but I'm using Middleman and not rails. Not sure if them both being Ruby based is enough.

The fix seems to be to cast everything in the helper to a string.
This is what I've come up with:

```ruby
root = GULP_CONFIG['root']['dest'].gsub(/(.*).public\//, '/')
asset_path = type ? File.join(GULP_CONFIG['tasks'][type.to_s]['dest'].to_s, path.to_s) : path.to_s
asset_path = rev_manifest[asset_path].to_s if rev_manifest
asset_path = File.join(root.to_s, asset_path).to_s
File.absolute_path(asset_path, '/').to_s
```

I'm not sure if this would be useful in Rails or is even best practice in Ruby but it removed the errors from Middleman (also Ruby based).

**Comment by greypants** [comment]
Hmm... interesting. I imagine the same error would pop up in Rails. I don't see how this could hurt. I'll run it by some of our Ruby devs.

**Comment by greypants** [comment]
It seems like the only thing you'd need to stringify would be `path` though right? That's the bit that's being passed in as var? I think all the `File` methods return strings already. Does that work?

**Comment by craigmdennis** [comment]
Ok, I it's related specifically to my project and not something that needs to be explicitly handled by the helper. Something to do with the result of passing in variables into partials. If I `.to_s` the local, _before_ passing it into the gulp helper then I get no errors.

**Comment by greypants** [comment]
Cool. :+1:
