### ISSUE TITLE
Consider using cheerio to remove SVG fill attributes

### ISSUE THREAD

**Issue by craigmdennis** [vigetlabs/gulp-starter#279]
SVG store shows how to use cheerio to remove fill attributes https://github.com/w0rm/gulp-svgstore

When compiling an SVG as a sprite it is probably a good idea, as most software that exports as SVG will leave the `fill` attribute making the sprite unusable if you want to change the colour in CSS.

```js
.pipe(cheerio({
  run: function ($) {
    $('[fill]').removeAttr('fill');
  },
  parserOptions: { xmlMode: true }
}))
```

**Comment by craigmdennis** [comment]
Thinking about this some more, I'm not sure it needs to be included by default but could perhaps be an option. I realised there are quite a few SVG icons sets have multiple, specific colours.

**Comment by greypants** [comment]
@craigmdennis Yeah, the original contributor for this feature included cheerio as well, but I found myself needing to specify `fill="currentColor"` or a specific color pretty frequently, so I adjust my SVGs manually. The first trick lets you style 2-color svgs - one color with 'fill` and the other with `color`.

Here's where this task was originally born: https://github.com/vigetlabs/gulp-starter/pull/100
