### ISSUE TITLE
How would you go about including Modernizr, your way?

### ISSUE THREAD

**Issue by dillonbailey** [vigetlabs/gulp-starter#289]
Hey!

I've just been tinkering with this toolkit and absolutely love it, particularly as a great starting point for a new boilerplate.

One thing that's emerged almost immediately is if you feel there's a need for modernizr to fit into the picture? Typically I find it most useful for just filling the html class with all the nice helpers, but typically load it in the <head> in order to do so effectively from a vendor directory.

I've seen a couple people load Modernizr as an ES6 module, but feel that's a bit odd.

I suppose the "vendor" directory essentially becomes "node_modules" it would seem. SO as I feel your way of doing things is very clever and clean, how would you go about including Modernizr with this project as a baseline? Would you create a vendor directory in javascripts that gets built out separately to webpack?

Cheers!

DB

**Comment by alexcarpenter** [comment]
@dillonbailey have a look at https://github.com/doctyper/gulp-modernizr

Create a new task to generate a custom Modernizr file based on a per-project need.

**Comment by dillonbailey** [comment]
Thanks Alex, will take a look!

**Comment by greypants** [comment]
In the past, I used to make a `head.js` entrypoint that imported anything that needed to appear in the <head>, like Modernizr, Optimizely, or some tracking scripts:

vendor/index.js
```js
import './vendor/modernizr'
import './vendor/tracking-scripts'
```

config.json
```
 "js": {
      "src": "javascripts",
      "dest": "javascripts",
      "entries": {
        "app": ["./app.js"],
        "head: ["./vendor/index.js"]
      },
      "extensions": ["js", "json"],
      "babel": {
        "presets": ["es2015", "stage-1"],
        "plugins": []
      }
    }
```

Or if modernizer is the only thing, you could just point to that directly as the entry.
