### ISSUE TITLE
Node 6 support

### ISSUE THREAD

**Issue by evaryont** [vigetlabs/gulp-starter#302]
See also, #292.

I'm not sure what would need to be updated myself.

**Comment by greypants** [comment]
👍  Will look into it when I get the chance.

**Comment by stevenmirabito** [comment]
YMMV but I just upgraded all of the dependencies with [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) and everything appears to work on Node v6.3.0.

**Comment by greypants** [comment]
Should have this upgraded this week.

**Comment by fyllepo** [comment]
Thanks @stevenmirabito for suggesting that package, working perfectly on Node 6.2.0

**Comment by greypants** [comment]
I've got a couple of experimental branches with Node 6 support going:

https://github.com/vigetlabs/gulp-starter/tree/v3.2.0
https://github.com/vigetlabs/gulp-starter/tree/v4
https://github.com/vigetlabs/gulp-starter/tree/v4-scripts

Most of the new work is prepping this project to be npm-installable package, but node 6 support was added (and old versions dropped).

**Comment by greypants** [comment]
Node 6+ is a requirement for the next release (4.0.0)! Dropping support for 5.x and below.
