### ISSUE TITLE
Jekyll alternative HTML task.

### ISSUE THREAD

**Issue by fyllepo** [vigetlabs/gulp-starter#310]
Hi guys, I wondered if anybody else working with this package has successfully hooked up Jekyll?

The Jekyll compile isn't the problem, what I can't appear to get working is the BrowserSync reload.

**Background**
- I've removed Numjucks
- I've setup the Jekyll src folder as '/src/html'
- I've setup the Jekyll dist folder as '/_site/'
- I've configured BrowserSyncs' base dir to '_site'
- I've modded the html.js task, as below

**HTML Task**
```
var config = require('../config')
if(!config.tasks.html) return

var browserSync  = require('browser-sync')
var gulp         = require('gulp')
var cp           = require('child_process');
var exec         = cp.exec;

var htmlTask = function() {
  exec('jekyll build', null, function(err, stdout, stderr) {
    if (err) {
      console.log('Child process exited with error code', err.code);
      return
    }
    browserSync.reload({stream:true});
    console.log(stdout);
  });
}

gulp.task('html', htmlTask)
module.exports = htmlTask
```

**Comment by greypants** [comment]
Try removing `{ stream: true }` there.

Alternatively you can pass a `files` option to browserSync that will tell it to watch a glob and reload if a file there changes. You can add that in the config.json file. If you did, you'd remove references to BrowserSync in this file.

**Comment by greypants** [comment]
@talbs weren't you messing with this at one point?

**Comment by fyllepo** [comment]
Thanks @greypants for the suggestion, I've got this working with just calling an empty browserSync.reload().
