### ISSUE TITLE
browserSync not reloading after replacing template engine with gulp-jade

### ISSUE THREAD

**Issue by Sourouche** [vigetlabs/gulp-starter#316]
Hi,

I've replaced Nunjucks template engine with Jade and the html files generation is working fine into the public folder.

But, I can't make the auto refresh browser working, even when I'm specifiying the browserSync "files" options in the config.json file.

When the server is launching, I can't even get the "Connected to BrowserSync" message on my browser.

Please notice that my files seems to be well-watched as my terminal returns me "File changed: ..." and "Reloading Browsers..." messages when I make files changes.

If you have any idea to help me getting this issue resolved, It would be nice.

Thanks in advance.

**Comment by Sourouche** [comment]
It's fully my fault guys, deeply sorry. For testing, I created a jade file without any html or body tag inside so It couldn't inject the browser-sync client into the index file dynamically.

Sorry again :).

**Comment by Spunkie** [comment]
@Sourouche Would you mind sharing your gulp-starter jade implementation?

**Comment by Sourouche** [comment]
Hey @Spunkie, not so difficult to do it.

Nodejs already comes with a template engine. So, the only thing you have to do is to specify which one you want to use.

Here is my jade implementation in my server file :
`var jade = require('jade');`
`app.set('views', __dirname + '/src/views');`
`app.set('view engine', 'html');`
`app.engine('html', jade.renderFile);`

Then, you need to render you jade template dynamically or statically in your route.
For example :
`res.render( 'partials/project.jade', { page: 'project', project: project } );`
or
`res.render( 'partials/' + req.query.page + '.jade', { page: req.query.page, projects: projects } );`

The conclusion of these is that gulp is useless for compiling jade template into html in Nodejs :).
