### ISSUE TITLE
importing jQuery plugins 

### ISSUE THREAD

**Issue by stevieg83** [vigetlabs/gulp-starter#317]
Please forgive the dumb question, I'm still trying to wrap my head around the webpack and ES6 stuffs.

If I have `app.js` and I import jQuery like so:

```
import $ from 'jquery';
import jQuery from 'jquery';

// export for others scripts to use
window.$ = $;
window.jQuery = jQuery;

```

and then I do something like `import "jquery.slicknav.js"` the browser tells me that `jQuery is not defined`

What should the setup be for something like that?

**Comment by greypants** [comment]
Not a dumb question. Something everyone gets confused by when first getting into this stuff. This might help: http://stackoverflow.com/a/28989476/484545

**Comment by stevieg83** [comment]
thanks - still flummoxed :)
