### ISSUE TITLE
v4 Rails path-config.json

### ISSUE THREAD

**Issue by solomonhawk** [vigetlabs/gulp-starter#321]
@greypants What are your thoughts on this comment from Rysten:

> If `config/path-config.json` is required in non-dev/test environments, we'll want to add it to `config/deploy/config_files/` as well so when we run cap setup on a new server we'll generate the necessary path config.

This is kind of specific to the way we write Rails apps.. at least specific to the use of Capistrano for deployments. Should we leave a note in the README for `rails-init` or consider actually generating this file?

**Comment by greypants** [comment]
if the `config` folder is special to rails, we can move our asset config files somewhere else. So the root `config` folder isn't available to the file system on non-dev environments? I don't fully understand the comment.

**Comment by solomonhawk** [comment]
`path-config.json` does not depend on environment (it is the same across envs) so this is a non-issue.
