### ISSUE TITLE
Wait until HTML has rendered before reloading the browser

### ISSUE THREAD

**Issue by craigmdennis** [vigetlabs/gulp-starter#322]
I have switched to Jade from Nunjucks but the browser reload is triggered before the HTML has compiled (as I think it's just waiting for .jade files to have changed).

There is a recipe on BrowserSync about exactly this https://github.com/BrowserSync/recipes/tree/master/recipes/gulp.jade

The salient part of the recipe is:

```
/**
 * Important!!
 * Separate task for the reaction to `.jade` files
 */
gulp.task('jade-watch', ['templates'], reload);
```

Then in the default task:

```
gulp.watch('./app/*.jade',      ['jade-watch']);
```

However, I have been unable to integrate it with your stellar DRY gulp tasks because of how interconnected they are.

I'm willing to make a PR if I'm successful (as this may apply to Nunjucks as well?) but need some direction from yourself :)

**Comment by akuales** [comment]
Did you have any luck with your jade-workflow? I'm trying to add twig in favor of Nunjucks and the default-gulp task creates the correct html file out of the twigs. 
But I cannot manage to make the watch-task run when editing any twig files, even though the glob should be fine.

**Comment by greypants** [comment]
I believe this is fixed in the `blendid` branch. Re-open if not.
