### ISSUE TITLE
Receiving Error bootstrap 67a9c4c…:567Uncaught Error: Cannot find module "./app.js"

### ISSUE THREAD

**Issue by interglobalmedia** [vigetlabs/gulp-starter#324]
I'm receiving the following error in the console:
bootstrap 67a9c4c…:567Uncaught Error: Cannot find module "./app.js"
webpackMissingModule	@	bootstrap 67a9c4c…:567
(anonymous function)	@	bootstrap 67a9c4c…:567
__webpack_require__	@	bootstrap 67a9c4c…:544
(anonymous function)	@	bootstrap 67a9c4c…:567
(anonymous function)	@	bootstrap 67a9c4c…:567

And I'm getting these errors in Terminal:

ERROR in ./src/javascripts/app.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at /Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at /Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /Users/mariacam/Development/tic-tac-toe/xoApp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
 @ multi app
webpack: bundle is now VALID.

As a result, my javascript is no longer working properly.

I originally was running this with Node 4.4.7 and npm 2+. Yesterday I upgraded to Node 6.5 and npm 3.10.3. I also made sure that my dependencies were updated. Still had the issue afterwards.

**Comment by Imaginarydesign** [comment]
Hello,

I had the same problem.

An upgrade to babel-core@6.10.4 may solve the problem. 
At least this did it im my case.

**Comment by QuentinGibson** [comment]
Had the same problem and @Imaginarydesign solution of upgrading babel-core to 6.10.4 worked for me also.

**Comment by joemidi** [comment]
Just ran into this problem and @Imaginarydesign's solution fixed it nicely.
