### ISSUE TITLE
the initial file must be index.js in the gulpfile.js directory?

### ISSUE THREAD

**Issue by khty2000** [vigetlabs/gulp-starter#331]
i have found the feature which using gulpfile.js as a directory and setting initial file as index.js only at this project . can anyone help me find some docs or articles that interpret this principle？

**Comment by greypants** [comment]
It takes advantage of how Node resolves modules. Node will look first for a file name (`gulpfile.js`). If not found, it will then look for a directory with that name, containing an index file. (`gulpfile.js/index.js`).

**Comment by greypants** [comment]
Node module documentation: https://nodejs.org/api/modules.html#modules_folders_as_modules
