### ISSUE TITLE
Gulp throwing 'undefined' or 'no mixin' errors when they are compiling fine 

### ISSUE THREAD

**Issue by Joshuwar** [vigetlabs/gulp-starter#332]
Could be down to my not fully understanding Webpack, but I'm getting a strange behaviour: whenever I save a .scss file, triggering gulp, I get errors saying that mixins or variables are not defined. However, the css compiles fine, actually applying all the variables/mixins it claims to have been not defined.

The complete message looks like this:
```
[10:50:26] gulp-notify: [Error running Gulp] Error in plugin 'gulp-sass'
Message:
    src/stylesheets/styles.scss
Error:
Undefined variable:
"$field-colour".
        on line 9 of stdin
>> 	background-color:
$field-colour;
   -------------------^

Details:
    status:
1
    file:
stdin
    line:
9
    column:
20
    formatted:
Error:
Undefined variable:
"$field-colour".
        on line 9 of stdin
>> 	background-color:
$field-colour;
   -------------------^

    messageFormatted:
src/stylesheets/styles.scss
Error:
Undefined variable:
"$field-colour".
        on line 9 of stdin
>> 	background-color:
$field-colour;
   -------------------^

    messageOriginal:
Undefined variable:
"$field-colour".
    relativePath:
src/stylesheets/styles.scss
[BS] 1 file changed (app.css)
```

**Comment by greypants** [comment]
When you save a file without prefixing it with an underscore, it gets rendered as it's own file (which doesn't import your variables or mixins). So if you're just importing the file into app.sass/.scss, rename your file to `_styles.scss`.
