### ISSUE TITLE
Old dependencies?

### ISSUE THREAD

**Issue by NoLooseEnds** [vigetlabs/gulp-starter#339]
Hi, I just checked this repo out and sto set up this, and I get quite a lot of dependencies warnings. 

> warning mocha > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> warning mocha > glob > graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> warning browser-sync > resp-modifier > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> warning mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
> warning gulp-nunjucks-render > through2 > xtend > object-keys@0.4.0:
> warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> warning browser-sync > localtunnel > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

Any reason that you guys don't update? If it ain't broken, don't fix it, etc?

**Comment by joemidi** [comment]
These might actually be the dependencies themselves not being up to date, rather than this project itself.

**Comment by NoLooseEnds** [comment]
No, you can update the "package.json" with new versions and get the newer versions of the dependencies. No problem.

But it could break something if i.e on dependency has changed the way it does stuff. Hence my questions. :)

**Comment by joemidi** [comment]
Yea, that's fine, but what I'm saying is dependencies of dependencies might not be up to date, so for `gulp-nunjucks-render` this project is using the [latest version 2.0.0](https://github.com/vigetlabs/gulp-starter/blob/master/package.json#L46), so as far as this project is concerned, its up to date.

```Shell
warning gulp-nunjucks-render > through2 > xtend > object-keys@0.4.0:
```

However, the warning comes from `object-keys@0.4.0` which is a dependency of `xtend` which is a dependency of `through2`, which is the dependency listed in `gulp-nunjucks-render`.

**Comment by NoLooseEnds** [comment]
That is an issue also I guess, but some of the (main) dependencies is outdated. And I want to know if there is an reason for that? (i.e the If it ain't broke, don't fix it).

**Comment by joemidi** [comment]
I think it's more the case of not having the time to update and run some tests.

You could do that and then make a pull request.

**Comment by NoLooseEnds** [comment]
True, I could – and I have done it locally, but I'm probably not skilled enough to test every aspect of this – so making a pull request is maybe not such a good idea?

Everything seems to work at least, but only tested on the demo site. Both during development ("run gulp") and production ("run production")

**Comment by NoLooseEnds** [comment]
I tried (for the first time) to add a pull request. We'll see if it's good enough.

**Comment by greypants** [comment]
dependencies will be up to date in the next release.
