### ISSUE TITLE
Javascript subfolders?

### ISSUE THREAD

**Issue by chrisbrenn** [vigetlabs/gulp-starter#347]
First of all - great kit!

My question: is it possible to add subfolders under "src/javascripts/subfolder" with other .js files and generate minified folder under "public/javascript/subfolder"? Currently there is only a option for only one js file names "app.js".

thanks,
chris.

**Comment by greypants** [comment]
If you're wanting to concat an minify the contents of a folder, you'd have to list out the files individually in the array.

```js
 javascripts: {
    entries: {
      app: ["./app.js"],
      vendor: ["./vendor/foo.js", "./vendor/bar.js", "./vendor/baz.js"]
    },
  },
```
