### ISSUE TITLE
Support custom tasks

### ISSUE THREAD

**Issue by greypants** [vigetlabs/gulp-starter#352]
It'd be great to be able to override  specific tasks (like css or html with postcss or jade), and add additional tasks, without having to completely eject the package. Let's brainstorm on the best way to go about this.

**Comment by greypants** [comment]
Thoughts so far: 

in `task-config.js`, allow overriding one of the default tasks by checking for an optional `task` property that would point to a gulp task to run instead of the default. 

```js
stylesheets: {
  task: require('./my-postCSS-gulp-task')
}
```

We could even ship a few pre-baked alternative tasks with `blendid`

```js
stylesheets: {
  task: require('blendid/tasks/post-css')
}
```

The second thing to handle is additional completely new tasks. The only tricky thing here is if they need to run at a particular point, like before JS compiles, or after files have been revved. We could just expose a couple of options that would take arrays, and run the tasks at teh specified order:

```js
prebuildTasks: [require('./my-extra-task-that-runs-before-compiling')],
postbuildTasks: [require('./my-extra-task-that-relies-on-everything-being-compiled-already')']
```

Custom tasks might be defined as functions that expect `gulp`, as well as the `PATH_CONFIG` and `TASK_CONFIG` files, and return a gulp task.

```js
// my-custom-blendid-task.js
function myCoolTask(gulp, PATH_CONFIG, TASK_CONFIG) {
  return function() {
    return gulp.src(PATH_CONFIG.myCustomThing.src)
       .pipe(somethingCool(TASK_CONFIG.myCustomThing))
      .dest(PATH_config.foo.dest)
  }
}
```

**Comment by solomonhawk** [comment]
I think having a simple interface that custom tasks can adhere to is smart. Perhaps we pass both `gulp` and the entire `config` object?

It would be great to have some input from other developers about what kinds of workflows they want to support so that we can better assess what escape hatches are needed. A list of use-cases to test against would make this far easier to accomplish.

**Comment by greypants** [comment]
I'm thinking of accepting an `additionalTasks` configuration object that would be shaped like:

```js
additionalTasks: {
    initialize(gulp, PATH_CONFIG, TASK_CONFIG) {
      gulp.task('compressImages', function() {
        // my custom task
      })
    },
    prebuild: [],
    postbuild: ['compressImages']
  }
```

`additionalTasks.initialize` would be where you could add additional gulp tasks. Then the `prebuild` and `postbuild` options would define when and in what order the additional tasks should run.

**Comment by sntiagomoreno** [comment]
Hi, I'm using a custom task to be able to use Gulp insted of Nunjucks. However the file never gets compiles so when BrowserSync runs it can't file the index.html file. Is there anything else I have to configure?

```
alternateTask: function(gulp, PATH_CONFIG, TASK_CONFIG) {
      // Pug task instead of Nunjucks
      return function() {
        console.log(PATH_CONFIG.html.src + ', ' + PATH_CONFIG.html.dest);
        gulp
          .src(PATH_CONFIG.html.src)
          .pipe(pug())
          .pipe(gulp.dest(PATH_CONFIG.html.dest))    }
    }
```

**Comment by greypants** [comment]
It's possible there's a bug. Feel free to open as a new issue.

**Comment by Tim152** [comment]
@sntiagomoreno try to add `.pipe(browserSync.stream());` and don't forget import browserSync `const browserSync = require('browser-sync')`
