### ISSUE TITLE
Import bootstrap4

### ISSUE THREAD

**Issue by felek000** [vigetlabs/gulp-starter#367]
Hello i install bootstrap 4 via npm so source files are in node modules.
I import scss files and works fine.

Now i want to add js files. 
In modules i create folder b4.js and import jquery after that i import modules from bootstrap. Iget folowing error that jQuery is not defind in import file.

code
```
import jQuery from '../../../node_modules/jquery/dist/jquery';
import '../../../node_modules/bootstrap/js/dist/alert'
```

I also import file in app.js

My question is how can i import bootstrap js to project when i add it like simple cdn file it works fine.

**Comment by cesasol** [comment]
Prefer npm over bower, for example for bootstrap 4 you can use:
``` js
// jQuery
var $ = require('jquery');
global.jQuery = $;
// All of bootstrap
require('bootstrap');
// only alert
require('bootstrap/js/src/alert.js');
```
Webpack in this way resolves js from src/javascripts and from node_modules

**Comment by jbielick** [comment]
Bootstrap4 uses an in-house dependency system, so Webpack won't be able to resolve any dependencies in the bootstrap javascript modules. You may find [this readme](https://github.com/shakacode/bootstrap-loader#bootstrap-4-internal-dependency-solution) helpful. Without the Provide plugin definitions like that example has, none of the bootstrap javascript works correctly.

**Comment by cannap** [comment]
maybe you can try https://github.com/thednp/bootstrap.native
