### ISSUE TITLE
Run as dependency

### ISSUE THREAD

**Issue by rcreate** [vigetlabs/gulp-starter#374]
I'm using gulp-starter or blendid by invoking the npm scripts from my own package.json:
```
"scripts": {
  "production": "npm explore queo-blendid -- npm run build",
  ...
}
```

When I invoke this command on windows, process.env.PWD isn't set, so process.cwd() + '../../' is used for that (the ancestor package).
When I invoke it on unix os process.env.PWD is set and the root of gulp-starter package is used for loading configs and file sources.

Is it the wrong way to invoke gulp-starter / blendid or why is the behaviour different on this two operating systems?

I think, process.env.PWD should always be set to ../../ and if there's no config the value should be set back to current working dirctory ( process.cwd() ).

**Comment by greypants** [comment]
what does `npm explore` do? The way I run this via npm scripts is

```json
"scripts": {
  "production": "blendid -- build"
}
```

though, that only works on unix systems, as it runs a bash script installed to `node_modules/.bin/blendid`

All this does is start gulp using the blendid gulpfile and tasks. Options passed map to gulp task names (`build` in this case)

@gregkohn what did you guys end up putting in scripts to get it runnable in windows?

**Comment by rcreate** [comment]
Thanks for your notice about how you are running blendid from outside. I spent my time today to check if I can also use this nice way. At least I figured out that we should use .js scripts instead of .sh scripts to trigger gulp. This is why I made the current PR of mine.

This issue means another problem. The problem on win32 systems is about "process.env.PWD". If you invoke blendid from outside the path in process.env.PWD is set to the root directory of the blendid package. Only on win32 systems the variable is set to "cwd()+'../../'".
This is inconsistent I think...

After my research today I suggest that we always set process.env.PWD to process.cwd() and use the argument "--cwd" to point cwd to the root of the web project when invoking gulp via the binary script (/bin/blendid.sh).

Do you agree?

**Comment by greypants** [comment]
Resolved in the `blendid` branch.
