### ISSUE TITLE
Service Workers

### ISSUE THREAD

**Issue by mcneela86** [vigetlabs/gulp-starter#379]
I have built a site using this repo as my starting point and I really love it, it have everything I needed to build my site.

The next step for me is adding service workers, but in order to do that I need to have a seperate 'service-workers.js' file, when I add this file to the src/javascript directory it does not get moved across in the build process.

I have also tried adding the file to the gulpfile.js/config.json, under the 'js' task where is says "./app.js". This concatenates the two files and causes an error.

Any ideas how I can do this, I am really stuck?

**Comment by leonardoelias** [comment]
Would be a: 

<script src="service-workers.js"></script>

**Comment by greypants** [comment]
Sure, just add another key to the entries object. The key is the name of the file that will get generated, and the value should point to the entry point for that bundle:

```js
{
  "app": "./app.js",
  "service-workers: "./service-workers.js"
}
```
