### ISSUE TITLE
Combined JS files breaks scripts?

### ISSUE THREAD

**Issue by NoLooseEnds** [vigetlabs/gulp-starter#383]
I'm not that experienced with this, but as far as I can figure out, it seems like that the "gulp-starter" JS settings somehow breaks stuff.

If I combine and minify scripts via "gulp-starter", etc. I get:
`Uncaught TypeError: $(...).hcSticky is not a function`
 
If I load the script separate from the static folder or CDN, it works. I get no errors. 

This is not just a problem with this script, but multiple.

Any input on this?

**Comment by greypants** [comment]
If you're loading plugins that are expecting a `$` or `jQuery` object to be globally accessible on`window`,  you'll need to do something like

```
import jQuery from 'jquery'

window.jQuery = jQuery
```

and set that before importing the plugins looking for `window.jQuery` to exist.

Generally modular code avoids putting things on `window` and you just import what you need to the files that need them.

Here's a decent read on how modules work: https://strongloop.com/strongblog/an-introduction-to-javascript-es6-modules/

**Comment by NoLooseEnds** [comment]
Thanks for pointing me in the right direction. Hopefully I will figure it out.

**Comment by stoqe** [comment]
@NoLooseEnds Did you figure this out? I'm trying to incorporate Blendid for a static site build on a pre-exisiting site which has a bunch a jquery plugins. I think my issues are being caused by @greypants' point (needing to load plugins that require global access) but javascript is quite beyond me. For the moment I've have the js files hardcoded in and stored in static/js.

**Comment by greypants** [comment]
@stoqe Check out the [`provide` option](https://github.com/vigetlabs/blendid#provide):  - it maps directly to the [webpack `ProvidePlugin` ](https://webpack.github.io/docs/list-of-plugins.html#provideplugin
)

So make sure jquery is yarn installed, then pass this config
```
provide: {
    $: "jquery"
}
```
And jquery should be made available to all your code. Might be worth explaining the option a little more in the README.

**Comment by NoLooseEnds** [comment]
@stoqe I ended up making a static folder for jquery plugins. But @greypants solution is probably a better option.
