### ISSUE TITLE
Typo in SVG sprite macro?

### ISSUE THREAD

**Issue by kty** [vigetlabs/gulp-starter#390]
I noticed the `<use>` tag in SVG sprite macro (`src/html/macros/helpers.html`) is closed twice, first as a self-closing tag, then with a separate closing tag:

```html
<use xlink:href='images/sprites.svg#{{id}}' /></use>
```

Is this a typo or a workaround for some cross-browser issue? 

I know older IEs didn't allow `<use>` tags to be self-closed. I had an issue with SVG sprites in IE10, saw warnings in console related to that and changed the above line to:

```html
<use xlink:href='images/sprites.svg#{{id}}' ></use>
```

I saw no change in behaviour, but at least the warnings disappeared, so shouldn't this be the correct form?

**Comment by greypants** [comment]
whoops. Yeah, you're totally right. Pull request that!

**Comment by Iuriy-Budnikov** [comment]
fui, svg sprites doesne work in ie :(

**Comment by greypants** [comment]
@Iuriy-Budnikov you have to use something like [inline-svg-sprite](https://github.com/vigetlabs/inline-svg-sprite) or [svg4everybody](https://github.com/jonathantneal/svg4everybody) for IE compatibility

**Comment by Iuriy-Budnikov** [comment]
@greypants thanks! svg4everybody – it works well.

**Comment by greypants** [comment]
Fixed the typo in the `blendid` branch - merging soon!
