### ISSUE TITLE
Add dot files to static as config option

### ISSUE THREAD

**Issue by devinle** [vigetlabs/gulp-starter#392]
Great work on this! It's running super slick so far.

One comment/suggestion I have. I'm working on a firebase project which includes a .firebaserc file. I've added this file to static, but static doesn't pickup on dot files. I configured it to do so on my local as a test, might be nice to have an option to pass dot: true (or something of that nature) in the task-config.js file. I want this file to transfer into the main dest directory do I can run a firebase deploy from the dest root.

Thoughts?

Thanks.

**Comment by greypants** [comment]
huh. Didn't realize it's not copying dotfiles. Thanks for catching that! I think it should be default. Let's look into why it's not.

Are you using `blendid` or `master`?

**Comment by greypants** [comment]
Pushed up and cut a new `blendid` release (4.0.0-blendid-beta-20). `yarn upgrade blendid` and you should be good to go. Thanks!

**Comment by devinle** [comment]
Amazing! Thanks for looking into it so quickly!
