### ISSUE TITLE
npm start and public/javascripts (angularjs)

### ISSUE THREAD

**Issue by james-lee-it** [vigetlabs/gulp-starter#394]
I am building angularjs with gulp-starter, and I ran into some challenges.

I notice that after running 'npm start', there is no 'public/javascripts' files. Whilst running 'npm run production', 'public/javascripts' folder and files are produced.

I looked into config.json, and I understood that 'npm start' runs from public folder, not src folder. So, what I understand is that I need to have js files in 'public/javascripts' in order to watch and develop my js files.

Any help is greatly appreciated. And any experience on how to use gulp-starter with AngularJS would be great. Thanks!

**Comment by greypants** [comment]
The js files in development are served via webpack middleware, and are watched and reloaded by that as well. This bit is set up in the browserSync task. Files don't actually get written to disk in the dev task (npm start)
