### ISSUE TITLE
Selective compiling? (i.e just compile CSS for production)

### ISSUE THREAD

**Issue by NoLooseEnds** [vigetlabs/gulp-starter#397]
I have static site, and if there is i.e a small change to the CSS, all the images gets a new hash, and needs to be reuploaded. 

Is there a way to just update CSS (and maybe HTML, to get the new CSS hash), and not the image files? That would only take a fraction of the time.

**Comment by greypants** [comment]
Hmm....the images *shouldn't* get a new hash unless they've been changed... the md5 hashes are deterministic, and should output the same result every time, unless the file contents have changed. 

Is that not the case for you? If they're changing every time, or whenever the css changes, we've got a bug to figure out!

**Comment by NoLooseEnds** [comment]
Sorry, this is my mistake. I think I must have imagined it all. I just checked and the hash stays the same.
