### ISSUE TITLE
Can't see any other url but index in development.  "Refused to execute inline script..."

### ISSUE THREAD

**Issue by louisnovick** [vigetlabs/gulp-starter#399]
Starting up and going to /page-name is throwing this error.  If I compile the site and view the html files within the public folder its fine.  Not sure what's going on here. 
`Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-8U0IjmKhdF6muyTAHYlt46GTDHbWDTClf0ZpO3SBmxs='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.`

Node -v v7.4.0

The weird part is everything was working at a prior time.  It's just been a while since I've touched this project.

UPDATE - `yarn demo` also serves each page fine, problem only seems to be during watch task.

**Comment by louisnovick** [comment]
I was assuming that the files would work without .html appended to the end.  That was the issue.  Sorry about that.

**Comment by greypants** [comment]
ah yeah. You'd have to configure your server to work like that.
