### ISSUE TITLE
Webpack 2

### ISSUE THREAD

**Issue by maoueh** [vigetlabs/gulp-starter#407]
Is there any plans to move Blendid to Webpack 2?

**Comment by greypants** [comment]
Absolutely! Pull requests will be accepted! If no one else gets to it, I do have a solid week coming up in my calendar to bang out the last few things, with that being a top priority along with custom task support #352

**Comment by maoueh** [comment]
Ok great, I would be happy to contribute. Will try to provide something before your week arrive.

**Comment by greypants** [comment]
Done, and merged with the `blendid` branch!
