### ISSUE TITLE
Expects node-sass-glob-importer to be installed

### ISSUE THREAD

**Issue by tommymarshall** [vigetlabs/gulp-starter#408]
Otherwise you get an error that it can't find it, though not sure if it being included makes sense if it's an anti-pattern?

**Comment by greypants** [comment]
Not sure I follow... what's the error? I'm not currently including `node-sass-glob-importer`, though it's been discussed, and I'm open to adding it. Are you getting a warning somewhere?

**Comment by greypants** [comment]
Though you can add this yourself through the sass options in `task-config.js`:

```js
var sass = require('node-sass');
var globImporter = require('node-sass-glob-importer');
...
stylesheheets: {
  sass: {
    importer: globImporter()
  }
}
```

**Comment by tommymarshall** [comment]
Sure! So, the error was encountered after installing blendid, it would bark when running `blendid` and the build would fail saying it can't find glob importer. But maybe this has been resolved? (I'm without a computer ATM, but perhaps you didn't encounter the error because you had glob imported installed globally?)

**Comment by tommymarshall** [comment]
Going to go ahead and close for now. I can reopen if I encounter the problem later.

**Comment by greypants** [comment]
I did a global search, and couldn't find `node-sass-glob-importer` anywhere... I don't *think* anything is expecting it. But yeah, lemme know if you hit this again.
