### ISSUE TITLE
Cannot resolve module 'fs' after including sendgrid

### ISSUE THREAD

**Issue by xavianaxw** [vigetlabs/gulp-starter#410]
For Blendid

Package: https://www.npmjs.com/package/sendgrid

The Error log
```
ERROR in ../sendgrid/lib/helpers/inbound/parse.js
Module not found: Error: Cannot resolve module 'fs' in /Users/xavianaxw/Code/honestfox/node_modules/sendgrid/lib/helpers/inbound
 @ ../sendgrid/lib/helpers/inbound/parse.js 3:9-22

ERROR in ../mime/mime.js
Module not found: Error: Cannot resolve module 'fs' in /Users/xavianaxw/Code/honestfox/node_modules/mime
 @ ../mime/mime.js 2:9-22

ERROR in ../uue/uue.js
Module not found: Error: Cannot resolve module 'fs' in /Users/xavianaxw/Code/honestfox/node_modules/uue
 @ ../uue/uue.js 1:9-22
```

I found a solution for this on another repo [here](https://github.com/pugjs/pug-loader/issues/8#issuecomment-55568520) where I'm suppose to add the following code into my config.

```
node: {
  fs: "empty"
}
```

Currently I added this to my `webpack-multi-config.js` file in `node_modules/blendid` but I'm looking for a way to manage it from my root folder's `task-config.js`

**Comment by greypants** [comment]
Just a feature yesterday that lets you get at the full `webpackConfig` object for modification through a `customizeWebpackConfig` option.  Here's the documentation in the readme: https://github.com/vigetlabs/gulp-starter/tree/blendid#customizewebpackconfig

Let me know if that works out for you!

**Comment by greypants** [comment]
Oh - you'll need to install the specific release: 

`yarn update blendid@4.0.0-rc.11`

**Comment by xavianaxw** [comment]
Awesome! I'll give it a go @greypants
