### ISSUE TITLE
Error on fresh install of blendid 4.0.0-rc.12

### ISSUE THREAD

**Issue by xavianaxw** [vigetlabs/gulp-starter#419]
Current version: 4.0.0-rc.12

## The Problem?
```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.<anonymous> (/Users/xavianaxw/Code/xavianetti/node_modules/blendid/gulpfile.js/lib/task-defaults.js:58:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

## How to replicate?
`yarn add blendid`
`yarn run blendid -- init`

## How to solve this?
As what the error message implicates, it seems that it is pointing to this line of code under the `ghPages` section of `node_modules/blendid/gulpfile.js/lib/task-defaults.js`
`cacheDir: path.join(os.tmpdir(), pkg.name)`

I did a simple `console.log` on both `os.tmpdir()` and `pkg.name` and realized that `pkg.name` was undefined.

Enter `name` property in `package.json`, so change from
```
{
  "dependencies": {
    "blendid": "^4.0.0-rc.12"
  }
}
```

to this

```
{
  "name": "xavianetti",
  "dependencies": {
    "blendid": "^4.0.0-rc.12"
  }
}
```

Enter your init command: `yarn run blendid -- init` and you're good to go

## Or 
Just run `npm init` and set up your `package.json` with the setup helper and run `yarn run blendid -- init` after you're done with that

and you end up with something like this
```
{
  "dependencies": {
    "blendid": "^4.0.0-rc.12"
  },
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}
```

Not much of an issue on blendid's part but just thought might be helpful for anyone who comes across this problem, since this wasn't a problem in previous install of blendid (early February)

Have a great weekend y'all!

**Comment by greypants** [comment]
JUST ran into this myself. Pushed up rc.13 with the fix. I added the `yarn init` step back to the quickstart section of the README, as well as provided a fallback for `pkg.name`.

Thanks!

**Comment by xavianaxw** [comment]
No worries! @greypants keep up the good work!
