### ISSUE TITLE
Version 2 / Feedback

### ISSUE THREAD

**Issue by greypants** [vigetlabs/gulp-starter#97]
I'm working on semi-large refactor of this project in a 2.0 branch: 
https://github.com/greypants/gulp-starter/tree/2.0

Changes:
- Full asset pipeline and static html compiling with Swig
- New directory structure
- Production mode w/ css/js compression + filename revisioning
- Remove old examples and extraneous dependecies
- Use gulp-watch to catch new files
- Upgrade misc. dependencies (BrowserSync 2!)
- Move browserify transform options out of package.json

My plan is to keep the existing version (that matches the original blog post more closely) around in a 1.0 branch and tag it for reference, and merge 2.0 into master. 

Test it out, and leave your comments below.

**Comment by ieugen** [comment]
Doesn't compile jsx files (babel can do it)

**Comment by renestalder** [comment]
The first thing I notice is that the asset folder is inside the gulp folder. Maybe this is only for testing purposes, but in most cases I want my build processes separated from my source files.

**Comment by synapticism** [comment]
Would you have any interest in integrating a task to build SVG icon sheets (i.e. using gulp-svgstore) in addition to icon fonts? Great work by the way; I learned a lot from following this project!

**Comment by Spy-Seth** [comment]
I agree with @renestalder. The asset folder should be outside the build process files. It's not mandatory to be in `src` folder it's a common use case.

**Comment by ieugen** [comment]
+1 to sources outside the buid. Comming from a java world, the conventions are (maven, gradle, etc) [1]: 
- /src/main/ - tree with sources used for main application 
- /src/test/ - tree for test sources
- /target or /build - output of the build process, can be deleted and is re-create by the build process

[1] http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by greypants** [comment]
Re: SVG sprites - yeah, I could look at adding it. I have a task from a previous project lying around somewhere. I think I used https://github.com/jkphl/gulp-svg-sprite

re: Folder structure - yeah, it does feel weird. It came from https://github.com/greypants/gulp-rails-pipeline, where there already was a [rails] assets pipeline- which needed to stay in place. I put my assets in the gulp folder to differentiate between the two asset pipelines. In my mind, it made sense because they *are* all gulp assets (assets to be processed by Gulp tasks).

But maybe that only makes sense in that specific context. What about something like this? Definitely influenced by Rails.

![image](https://cloud.githubusercontent.com/assets/647549/6373802/09616c1e-bcdb-11e4-8de6-5bd3418aab10.png)

Really, no matter what, people will likely have to move some folders around to make this work with their stack. But this can also be used as static site generator, and should feel right as a standalone setup too.

Note that:
- I removed the original 'gulpfile.js` file
- I renamed the `gulp` folder to `gulpfile.js` and put the `requireDir('./tasks')` into an `index.js` file within it. - Running `gulp` works just the same, and `gulpfile.js/index.js` gets picked up and run.

I think this makes sense, as that's exactly what the folder represents (a gulpfile).

**Comment by synapticism** [comment]
That folder trick is quite clever... and yeah, people are going to move things around anyway. Personally I follow the src/build/dist model for most things. I see you define directories at the top of the config file so it doesn't really matter so much what it ships with.

Re: SVG sprites, I have a working setup that I could contribute in a PR if that's your style and you're interested. The general approach I'm using can be seen [here](https://github.com/synapticism/pendrell/blob/master/gulp/tasks-active/svg.js) (SVG task), [here](https://github.com/synapticism/pendrell/blob/master/gulp/tasks-active/bower.js) (specialized Bower tasks to import icons), and [here](https://github.com/synapticism/pendrell/blob/master/gulp/tasks-active/bower.js) (config file with relevant settings under `svg`/`bower`). This might be a bit out of scope for a "starter" kit though, which is why I ask.

**Comment by greypants** [comment]
@synapticism I'm definitely open to Pull Requests, but I'd rather not add Bower as a dependency.

**Comment by synapticism** [comment]
@greypants That's cool. I'll think it over and see if there's any use to adding something along those lines to the project then. The SVG component can accept whatever people throw at it (I just happen to use Bower) so it might still be useful.

**Comment by synapticism** [comment]
Alright, I sent #100 to show you how that would look. No Bower required.

Two other (very) small bits of feedback:
1) I like having the config file in the root; it makes it a little easier to access when modifying a project.
2) It might be nice to switch from `gulp-autoprefixer` to `gulp-postcss`, a general wrapper for all PostCSS plugins (of which Autoprefixer is just one): https://github.com/w0rm/gulp-postcss

**Comment by pBun** [comment]
Might want to add a gulp task to copy the `/CNAME` file for production builds so there's a way to utilize Github's custom domain functionality.

I added the copyCNAME task to [the build-production file in a project I'm working on](https://github.com/pBun/multi-twitch/blob/master/gulpfile.js/tasks/build-production.js), but it's not the most graceful of solutions. It should probably be baked in with the deploy task. If I get some free time I'll take a crack at it and send over a pull request.

**Comment by kylemarimon** [comment]
[off-topic](well. kinda)

Does anyone know what negatives exist from appending a hash to image filenames and SEO? I understand its usefulness, when it comes to breaking the cache. But wouldn't that require google to re-index the image? If the old filename doesn't 404 is there an issue? My team at work doesn't feel that it's a good idea.

**Comment by noderat** [comment]
Is there a reason why wiredep isn't being used to automatically include bower packages?

**Comment by DJTB** [comment]
All the final changes are looking good.

Just a question though, the dependencies and devdependencies in package.json seem somewhat arbitrarily split. I feel like almost everything should be in devdeps since none of the modules are being packaged up for the browser.

**Comment by greypants** [comment]
@DJTB I agree. Originally the split came from a project where I was deploying to Heroku, which ignored dev dependencies. The only thing left in there were modules related to the test server that only ran locally. But Yeah, lets move everything back. There's a way to tell heroku to include devDependencies.

Other than that, all that's left before I merge this into amster is writing a good README.

**Comment by rctneil** [comment]
@greypants Any updates on the README? I have a current Rails app and tried to do a gulp integration myself which wasn't easy to work with and found this but not 100% sure on how to integrate this into my rails app.

**Comment by greypants** [comment]
@rctneil 

This is behind gulp-starter, but the key integration bits and ideas are there: Check out http://viget.com/extend/gulp-rails-asset-pipeline and https://github.com/vigetlabs/gulp-rails-pipeline

**Comment by greypants** [comment]
Merged!
